services:
    sitepackage_generator.generator:
        class: BK2K\Sitepackage\GeneratorBundle\Service\Generator\SitepackageGenerator

    sitepackage_generator.twig.extension.contentget:
        class: BK2K\Sitepackage\GeneratorBundle\Twig\ContentGetExtension
        tags:
            - { name: 'twig.extension' }

    sitepackage_generator.form_extention.button_icon:
        class: BK2K\Sitepackage\GeneratorBundle\Form\Extension\ButtonTypeIconExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }
